// AUTO-GENERATED by gen-bm25-browser.mjs from Automation/core/src/bm25.mjs.
// Do not hand-edit — re-run the generator instead so this never drifts from
// the canonical source. Exposes window.BM25 = { tokenize, scoreAndRank }.
(function(global){
// Pure BM25 scoring — zero Node-specific APIs, safe to run in a browser as-is
// (mirrored there by gen-bm25-browser.mjs -> shared/bm25.js) or import
// directly in any Node script (e.g. ncert-knowledge-base/build-subject-shards.mjs).
// tokenize() is copied verbatim from build-index.mjs (kept in lockstep there —
// both must tokenize identically or df/termFreq built by one is meaningless
// scored by the other); bm25Score() is copied verbatim from the existing
// retrieve.mjs files. This module does not read or write any index itself —
// callers hand it an already-loaded {docs, df, avgDocLen, docCount} object.

const K1 = 1.5;
const B = 0.75;

function tokenize(text) {
  // \p{M} (combining marks) must stay alongside \p{L} — Devanagari vowel
  // signs (matras like ो/ि/ा) are category Mark, not Letter, so without it
  // this regex silently strips every matra and shreds Hindi words into bare
  // consonants (कोशिका -> क श क) instead of leaving them intact.
  return String(text || '')
    .toLowerCase()
    .replace(/[^\p{L}\p{M}\p{N}\s]/gu, ' ')
    .split(/\s+/)
    .filter(w => w.length > 1);
}

function bm25Score(queryTerms, doc, df, docCount, avgDocLen) {
  let score = 0;
  for (const term of queryTerms) {
    const tf = doc.termFreq[term];
    if (!tf) continue;
    const docFreq = df[term] || 0;
    if (!docFreq) continue;
    const idf = Math.log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5));
    const norm = tf * (K1 + 1) / (tf + K1 * (1 - B + B * (doc.docLen / (avgDocLen || 1))));
    score += idf * norm;
  }
  return score;
}

// scoreAndRank(index, queryText, filter, topK) -> [{...doc fields except termFreq/docLen, score}]
// `index` is {docs, df, avgDocLen, docCount} (the same shape every retrieve.mjs
// in this repo already reads/writes). `filter` is an optional {field, value}
// restricting the pool before scoring (e.g. {field:'subject', value:'Geography'}).
function scoreAndRank(index, queryText, filter, topK) {
  if (!index || !index.docCount) return [];
  const queryTerms = [...new Set(tokenize(queryText))];
  let pool = index.docs;
  if (filter && filter.field && filter.value) {
    const wanted = String(filter.value).toLowerCase();
    pool = pool.filter(d => d[filter.field] && String(d[filter.field]).toLowerCase() === wanted);
  }
  const scored = pool
    .map(d => ({ ...d, score: bm25Score(queryTerms, d, index.df, index.docCount, index.avgDocLen) }))
    .filter(d => d.score > 0);
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, topK || 5).map(({ termFreq, docLen, ...rest }) => rest);
}

global.BM25 = { tokenize, scoreAndRank };
})(typeof window !== 'undefined' ? window : this);
