#!/usr/bin/env node
// EDITORIAL INTELLIGENCE — batch evaluator ("the automated 10-run evaluation
// mode"). Scores already-generated bundles (same shape as pending-notes/
// published-notes *.json) against real content-memory/published history AND
// against each other in sequence — closing a real gap confirmed during
// development: content-memory's variety machinery only ever compares a new
// article against PAST, SAVED, real publishes; it has zero visibility into
// sibling articles generated in the same un-saved test batch. Scoring each
// candidate against everything processed earlier in THIS run (in addition
// to real history) reproduces what the production loop would actually see
// if each one were published in sequence, which is the only way a same-
// session batch test can give an honest picture of the real repetition risk.
//
// Deliberately NOT a generator: this repo's own Automation/core/README.md
// documents that an API-key batch generator was built once and intentionally
// removed in favor of free, browser-driven generation (no per-article API
// cost). This script scores whatever you already generated by any means
// (ChatGPT, DeepSeek, Gemini, Claude...) — it never calls an AI itself.
//
// Usage:
//   node evaluate-batch.mjs <dir-of-bundles> [--exam "DSSSB"] [--subject "CDP"]
//     <dir-of-bundles>: a folder of *.json files shaped like
//       pending-notes/*.json: {seo, bodyHtml, publisherNotes, contentMemory,
//       examType?, subject?}. Processed in filename order — name them
//       run_1.json, run_2.json, ... if sequence matters to you.
//     --exam/--subject: optional override to filter which real
//       content-memory/published-notes records count as "history" (default:
//       read each bundle's own .examType/.subject field per-candidate).
//
// Prints one JSON report to stdout: { perRun: [...], aggregate: {...}, flags: [...] }

import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { evaluateCandidate, qualityDrift } from './editorial-evaluation.mjs';
import { filterMatching } from './editorial-intelligence.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const CONTENT_MEMORY_DIR = path.join(REPO_ROOT, 'Automation', 'content-memory');
const PUBLISHED_NOTES_DIR = path.join(REPO_ROOT, 'published-notes');

async function readJsonDir(dir) {
  let files = [];
  try { files = (await readdir(dir)).filter(f => f.endsWith('.json') && f !== 'index.json'); }
  catch { return []; }
  const out = [];
  for (const f of files) {
    try { out.push({ name: f, data: JSON.parse(await readFile(path.join(dir, f), 'utf8')) }); }
    catch { /* skip unparsable — not this script's job to fix the repo's data */ }
  }
  return out;
}

function parseArgs(argv) {
  const args = { dir: null, exam: null, subject: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--exam') args.exam = argv[++i];
    else if (argv[i] === '--subject') args.subject = argv[++i];
    else if (!args.dir) args.dir = argv[i];
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.dir) {
    console.error('Usage: node evaluate-batch.mjs <dir-of-bundles> [--exam "X"] [--subject "Y"]');
    process.exitCode = 2;
    return;
  }

  const [candidates, realContentMemory, realPublished] = await Promise.all([
    readJsonDir(args.dir),
    readJsonDir(CONTENT_MEMORY_DIR),
    readJsonDir(PUBLISHED_NOTES_DIR),
  ]);
  candidates.sort((a, b) => a.name.localeCompare(b.name));

  if (!candidates.length) {
    console.error(`No readable *.json bundles found in ${args.dir}`);
    process.exitCode = 1;
    return;
  }

  const realCmRecords = realContentMemory.map(r => r.data);
  const realBodiesBySlug = new Map(realPublished.map(r => [path.basename(r.name, '.json'), r.data.bodyHtml || '']));

  // Grows as the batch is processed — this is what closes the sibling-run
  // blind spot described above: candidate N is scored against real history
  // PLUS candidates 1..N-1 from this same batch.
  const siblingRecords = [];
  const siblingBodies = [];
  const perRun = [];

  for (const { name, data } of candidates) {
    const exam = args.exam || data.examType || '';
    const subject = args.subject || data.subject || '';
    const historicalRecords = filterMatching(realCmRecords, { exam, subject }).concat(siblingRecords);
    const historicalBodies = realPublished
      .filter(r => (r.data.examType || '') === exam || !exam)
      .map(r => ({ slug: path.basename(r.name, '.json'), bodyHtml: r.data.bodyHtml || '' }))
      .concat(siblingBodies);

    const report = evaluateCandidate(data, { historicalRecords, historicalBodies });
    perRun.push({ name, exam, subject, ...report });

    siblingRecords.push(data.contentMemory || {});
    siblingBodies.push({ slug: name, bodyHtml: data.bodyHtml || '' });
  }

  const qualityScores = perRun.map(r => r.quality.score);
  const noveltyScores = perRun.map(r => r.novelty);
  const avg = arr => arr.length ? Math.round((arr.reduce((a, b) => a + b, 0) / arr.length) * 1000) / 1000 : null;

  const flags = [];
  perRun.forEach(r => {
    if (r.repeatedCardSentences.length) flags.push(`${r.name}: reused ${r.repeatedCardSentences.length} verbatim card sentence(s) from a prior/historical run`);
    if (r.quality.score < 0.5) flags.push(`${r.name}: low quality score (${r.quality.score}) — ${r.quality.structuralErrors} structural error(s)`);
    if (r.novelty < 0.3) flags.push(`${r.name}: low novelty (${r.novelty}) — heavily overlapping a prior/historical run`);
  });

  const aggregate = {
    runCount: perRun.length,
    avgQuality: avg(qualityScores),
    avgNovelty: avg(noveltyScores),
    qualityDrift: qualityDrift(qualityScores),
    totalRepeatedCardSentences: perRun.reduce((s, r) => s + r.repeatedCardSentences.length, 0),
  };

  console.log(JSON.stringify({ perRun, aggregate, flags }, null, 2));
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
